version: '3'

services:
  client:
    build: client
    environment:
      GATEWAY_IP: 172.28.1.1
      DNS_SERVER_IP: 172.29.2.1
    privileged: true
    depends_on:
      - firewall
    cap_add:
      - NET_ADMIN
    networks: 
      intranet:
        ipv4_address: 172.28.2.1
  firewall:
    build: firewall
    depends_on:
      - dns_server
    privileged: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      intranet:
        ipv4_address: 172.28.1.1
      internet:
        ipv4_address: 172.29.1.1
  dns_server:
    build: dns_server
    depends_on:
      - server
    cap_add:
      - NET_ADMIN
    networks:
      internet:
        ipv4_address: 172.29.2.1
  server:
    build: server
    networks:
      internet:
        ipv4_address: 172.29.2.2
networks:
  # private company network (intranet)
  intranet:
    ipam:
      config:
        - subnet: 172.28.0.0/16
  # public network (internet)
  internet:
    ipam:
      config:
        - subnet: 172.29.0.0/16